{{- with .Values.envFrom }}
  {{- range . }}
    {{- if eq .type "configMap" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ include "omnix.namespace" $ }}
data:
  {{- range .files }}
{{ $.Files.Get .path | indent 2 }}
  {{- end }}
---
    {{- end }}
  {{- end }}
{{- end }}