apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "omnix.fullname" $ }}
  namespace: {{ include "omnix.namespace" $}}
  labels:
    app: {{ include "omnix.fullname" $ }}
    {{- range $key, $value := .Values.global.labels }}
    {{ $key}}: {{ $value }}
    {{- end}}
    {{- range $key, $value := .Values.deployment.labels }}
    {{ $key}}: {{ $value }}
    {{- end}}
  {{- with .Values.deployment.annotations }}
  annotations: 
    {{- range $key, $value := .}}
    {{ $key}}: {{ $value | quote }}
    {{- end}}
  {{- end}}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "omnix.fullname" $ }}
  {{- with .Values.deployment.strategy }}
  strategy: 
    type: {{ .type }}
    {{- if eq .type "RollingUpdate" }}
    rollingUpdate: 
      maxUnavailable: {{ dig "rollingUpdate" "maxUnavailable" 0 .}}
      maxSurge: {{ dig "rollingUpdate" "maxSurge" 1 . }} 
    {{- end }}
  {{- end }}

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "omnix.fullname" $ }}
      {{- with .Values.pod.annotations }}
      annotations: 
        {{- range $key, $value := .}}
        {{ $key }}: {{ $value | quote}}
        {{- end}}
      {{- end}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: 
        {{- toYaml . | nindent 8 }}
      {{- end}}
      {{- with .Values.serviceAccount.enable }}
      serviceAccountName: {{ $.Values.deployment.serviceAccountName | default (include "omnix.fullname" $) }}
      automountServiceAccountToken: {{ $.Values.serviceAccount.automountServiceAccountToken | default false}}
      {{- end}}
      {{- with .Values.securityContext }}
      securityContext:
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector}}
      nodeSelector: 
        {{- toYaml . | nindent 8 }}
      {{- end}}
      {{- with .Values.volumes}}
      volumes: 
        {{- range .}}
        - name: {{ .name }}
          {{ .type }}: 
            name: {{ .name}}
          {{- end}}
      {{- end}}
      containers:
        - name: {{ include "omnix.fullname" $}}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.ports }}
          ports:
            {{- range $key, $value := . }}
            - containerPort: {{ $value }}
              name: {{ $key }}
            {{- end }}
          {{- end }}
          {{- with .Values.containerArgs }}
          args: 
            {{- toYaml . | nindent 12}}
          {{- end}}
          {{- with .Values.containerCmd }}
          command: 
            {{- toYaml . | nindent 12}}
          {{- end}}
          {{- with .Values.env}}
          env:
          {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end}}
          {{- end}}
          {{- with .Values.envFrom }}
          envFrom:
          {{- range . }}
            {{- if eq .type "configMap" }}
            - configMapRef:
                name: {{ .name }}
            {{- else if eq .type "secret" }}
            - secretRef:
                name: {{ .name }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- with .Values.volumes}}
          volumeMounts: 
            {{- range . }}
              - name: {{ .name }}
                mountPath: {{ quote .mountPath }}
                {{- if .subPath }}
                subPath: {{ .subPath }}
                {{- end }}
                readOnly: true
                {{- end }}
          {{- end }}
          {{- with .Values.resources}}
          resources:
            {{- toYaml . | nindent 12}}
          {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12}}
          {{- end }}      
          {{- if .Values.livenessProbe.enable }}  
          livenessProbe:
            {{- toYaml (omit .Values.livenessProbe "enable") | nindent 12 }} 
          {{- end }}
          {{- if .Values.readinessProbe.enable }}  
          readinessProbe:
            {{- toYaml (omit .Values.readinessProbe "enable") | nindent 12 }} 
          {{- end }}
          